// @ts-check
import { defineConfig } from 'astro/config';
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import AutoImport from 'unplugin-auto-import/astro';

const componentsDirectory = fileURLToPath(new URL('./src/components/', import.meta.url));
const getComponentFiles = () => readdirSync(componentsDirectory, { recursive: true, encoding: 'utf8' })
	.filter((file) => file.endsWith('.astro'))
	.sort();
const componentNames = new Set();
// Astro's default exports are generated by its compiler, so register files directly.
const componentImports = getComponentFiles()
	.map((file) => {
		// fr/slide.contact.astro → FrSlideContact
		const pascalName = file.slice(0, -'.astro'.length)
			.split(/[/\\.\s_-]+/)
			.filter(Boolean)
			.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
			.join('');
		// A JavaScript identifier cannot start with a digit (1.slide.astro → _1Slide).
		const name = /^\d/.test(pascalName) ? `_${pascalName}` : pascalName;
		if (componentNames.has(name)) {
			throw new Error(`Duplicate Astro auto-import name "${name}" (${file})`);
		}
		componentNames.add(name);
		return { from: resolve(componentsDirectory, file), imports: [/** @type {[string, string]} */ (['default', name])] };
	});

/** @type {import('astro').AstroIntegration} */
const watchComponentImports = {
	name: 'watch-component-imports',
	hooks: {
		'astro:config:setup': ({ command, config, addWatchFile, updateConfig }) => {
			if (command !== 'dev') return;
			// Astro reloads its configuration when this generated file changes.
			const manifest = fileURLToPath(new URL('.astro/component-imports.json', config.root));
			const updateManifest = () => {
				const content = JSON.stringify(getComponentFiles());
				mkdirSync(dirname(manifest), { recursive: true });
				try {
					if (readFileSync(manifest, 'utf8') === content) return;
				} catch (error) {
					if (/** @type {NodeJS.ErrnoException} */ (error).code !== 'ENOENT') throw error;
				}
				writeFileSync(manifest, content);
			};
			updateManifest();
			addWatchFile(manifest);
			/** @type {(() => void) | undefined} */
			let cleanup;
			updateConfig({ vite: { plugins: [{
				name: 'watch-component-imports',
				configureServer(server) {
					/** @type {ReturnType<typeof setTimeout> | undefined} */
					let timer;
					/** @param {string} file */
					const onFileChange = (file) => {
						const path = relative(componentsDirectory, file);
						if (isAbsolute(path) || path.startsWith('..') || !path.endsWith('.astro')) return;
						clearTimeout(timer);
						// Group the unlink/add events of a rename into one reload.
						timer = setTimeout(updateManifest, 150);
					};
					server.watcher.add([componentsDirectory, manifest]);
					server.watcher.on('add', onFileChange).on('unlink', onFileChange);
					cleanup = () => {
						clearTimeout(timer);
						server.watcher.off('add', onFileChange).off('unlink', onFileChange);
					};
				},
				closeBundle() { cleanup?.(); },
			}] } });
		},
	},
};

const [owner = '', repository = ''] = (process.env.GITHUB_REPOSITORY ?? '').split('/');
const isGitHubPages = process.env.DEPLOY_TARGET === 'github-pages' && Boolean(owner && repository);
const isUserSite = repository === `${owner}.github.io`;

const i18n = {
    	locales: ["en", "fr", "nl"],
    	defaultLocale: "fr",
		routing: { prefixDefaultLocale: true }
  	}

// https://astro.build/config
export default defineConfig({
	site: isGitHubPages ? `https://${owner}.github.io` : process.env.SITE_URL || undefined,
	base: isGitHubPages ? (isUserSite ? '/' : `/${repository}`) : process.env.BASE_PATH || '/',
	i18n,
	integrations: [
		watchComponentImports,
		AutoImport({
			imports: componentImports,
			dts: './.astro/auto-imports.d.ts',
			dtsMode: 'overwrite',
		}),
	],
});
